version: "3.7"
services:

  backend:
    build:
      context: ./backend
    ports:
      - 8090:8080
    environment:
      - PORT=8080

  frontend:
    build:
      context: ./frontend
      args:
        - APIURL=http://localhost:8090
    ports:
      - 80:80